{"name": "test_addenterprise02", "status": "failed", "statusDetails": {"message": "AssertionError: assert '成功' == '找不到指定记录'\n  - 找不到指定记录\n  + 成功", "trace": "self = <testcase.test_enteripse.Testenterprise object at 0x0451A8B0>\n\n    def test_addenterprise02(self):            #禁用子企业员工\n            case_data = get_test_data(self.excel_data,'forbenterprise')\n            updatetoken(self.token, case_data)\n            takeid = re.findall(r'http://api.etmprot.etmcn.com/basic/v2/employee/(.*)/status', case_data[\"url\"])\n            sumid = str(int(takeid[0]) + 1)\n            data = json.loads(case_data['data'])\n            id = {\"id\": sumid}\n            data.update(id)\n            case_data['data'] = json.dumps(data)\n            new_url = \"http://api.etmprot.etmcn.com/basic/v2/employee/\"+sumid+\"/status\"\n            case_data[\"url\"] = new_url\n            res = send_request(case_data)\n>           assert case_data['expect_res'] == res[\"message\"]\nE           AssertionError: assert '成功' == '找不到指定记录'\nE             - 找不到指定记录\nE             + 成功\n\ntestcase\\test_enteripse.py:38: AssertionError"}, "start": 1600238709095, "stop": 1600238709318, "uuid": "544ce82a-7910-4dc1-91f1-21a1db22bef7", "historyId": "69b77e1e2b065c30e0831512271cd278", "testCaseId": "f9e45cfd03207d886b1ca05048b0c97b", "fullName": "testcase.test_enteripse.Testenterprise#test_addenterprise02", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_enteripse"}, {"name": "subSuite", "value": "Testenterprise"}, {"name": "host", "value": "TX5C3S1L7D31UYD"}, {"name": "thread", "value": "8104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_enteripse"}]}